name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build mkdocs-drawio
        run: |
          pip install poetry
          poetry install
      - name: Build and publish docs
        run: |
          cd examples
          source $(poetry env info --path)/bin/activate
          pip install -r requirements.txt
          mkdocs gh-deploy --force
